manipulator:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 20

    joint_1_controller:
        type: effort_controllers/JointPositionController
        joint: joint_1
        pid: {p: 100.0, i: 0.1, d: 10.0}
    joint_2_controller:
        type: effort_controllers/JointPositionController
        joint: joint_2
        pid: {p: 100.0, i: 0.1, d: 10.0}
    joint_3_controller:
        type: effort_controllers/JointPositionController
        joint: joint_3
        pid: {p: 100.0, i: 0.1, d: 10.0}

